data <- read.csv("C:\\Users\\hk838\\Downloads\\Customer_Transaction_Dataset.csv")
mean_purchase <- mean(data$Purchase_Amount)
median_purchase <- median(data$Purchase_Amount)
sd_purchase <- sd(data$Purchase_Amount)
correlation <- cor(data$Monthly_Income,
                   data$Purchase_Amount)
cat("========== BUSINESS ANALYTICS REPORT ==========\n")
cat("Average Purchase Amount :", mean_purchase, "\n")
cat("Median Purchase Amount :", median_purchase, "\n")
cat("Standard Deviation :", sd_purchase, "\n")
cat("Correlation :", correlation, "\n\n")
cat("Recommendations:\n")
cat("1. Focus on Premium Members.\n")
cat("2. Target high-income customers.\n")
cat("3. Improve customer satisfaction in low-rated stores.\n")
cat("4. Promote best-selling product categories.\n")
cat("5. Use personalized marketing campaigns.\n")